# Site settings
title: Recettes
description: > # this means to ignore newlines until "baseurl:"
  Artisan codeur cuisinier
url: "http://feston.github.io"
baseurl: "/recettes" 
# Build settings
markdown: kramdown
